
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hackerton
      uri: mongodb://localhost:27017/hackerton

naver:
  cloud:
    id: 8emvje69d2
    secret: FHQvAMq4g1NaYNsteCZH1cNE6Vbz433TR1xGGKhK